# -*- coding: utf-8 -*-
"""Python_capstone_project (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wAKR3rabF45tLghpjlQvXAtktSWmf05G
"""

# Project Title: OTP Verification System
# develop an OTP (One-Time Password) verification system in Python.
# The system should generate a 6-digit OTP and send it to the user's email address for verification.
# Upon receiving the OTP, the user should enter it into the system for validation.
# If the entered OTP matches the generated OTP, access should be granted;
# otherwise, access should be denied.

#INSTALLED NECESSARY WIDGETS
!pip install ipywidgets

import re
import numpy as np
from ipywidgets import widgets as wd
from IPython.display import display
import pandas as pd
import time

# Creating UI elements
email_input = wd.Text(description="Email:", placeholder="Please enter your Email address")
generate_otp_button = wd.Button(description="Generate OTP", button_style="info")
verify_otp_button = wd.Button(description="Verify OTP", button_style="info", disabled=True)
output = wd.Output()

# Display initial widgets
display(email_input, generate_otp_button, output)

# Global Variables
rand_otp = None
otp_input = None

# Function to validate email format
def is_valid_email(email):
    email_regexp = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    return bool(re.match(email_regexp, email))

# Function to generate a random 6-digit OTP
def create_otp():
    global rand_otp
    rand_otp = np.random.randint(100000, 999999)
    return rand_otp

# Function to display OTP input textbox
def add_otp_text():
    global otp_input
    otp_input = wd.Text(description="OTP:", placeholder="Enter the OTP")
    verify_otp_button.disabled = False  # Enable the button
    display(otp_input, verify_otp_button)

# Function to write OTP to a file
def send_otp(otp):
    with open("email_verif.txt", "w") as file:
        file.write(f"Please enter this OTP: {otp} to verify your email address.")

# Function to simulate entering OTP in the textbox
def enter_otp():
    global otp_input
    with open("email_verif.txt", "r") as file:
        content = file.read()
    print(f"File Content: {content}")  # Debug print to verify the file content
    otp = re.search(r"(\d+)", content).group(0)
    otp_input.value = otp  # Auto-fill the OTP into the textbox

# Generate OTP button action
def generate_otp(button):
    with output:
        output.clear_output()
        if email_input.value:
            if is_valid_email(email_input.value):
                generate_otp_button.disabled = True
                generated_otp = create_otp()
                add_otp_text()
                time.sleep(2)  # Simulate delay for sending OTP
                send_otp(generated_otp)
                enter_otp()
            else:
                print("Please enter a valid email address.")
        else:
            print("Please enter an email address.")

# Verify OTP button action
def verify_otp(button):
    with output:
        output.clear_output()
        print(f"Expected OTP: {rand_otp}")  # Debug print for OTP
        print(f"Entered OTP: {otp_input.value}")  # Debug print for entered value
        if otp_input.value == str(rand_otp):
            verify_otp_button.button_style = "success"
            print("Your email is verified successfully!")
        else:
            verify_otp_button.button_style = "danger"
            print("Invalid OTP. Please try again.")

# Button click handlers
generate_otp_button.on_click(generate_otp)
verify_otp_button.on_click(verify_otp)